#!/usr/bin/env bash
# scripts/ls-init.sh
# Creates localstack.override.tf and localstack.auto.tfvars in every Terraform
# layer, then runs `terraform init -reconfigure` for each one.
#
# These files are gitignored. Run `scripts/ls-teardown.sh` to remove them.
#
# Usage:
#   export LOCALSTACK_AUTH_TOKEN=<your-token>
#   scripts/ls-init.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENDPOINT="localhost.localstack.cloud:4566"
FAKE_UUID="00000000-0000-0000-0000-000000000000"

# ── Shared provider block (same for every layer) ──────────────────────────────
provider_block() {
  cat <<HCL

provider "azurerm" {
  features {}
  use_oidc                   = false
  subscription_id            = "${FAKE_UUID}"
  metadata_host              = "${ENDPOINT}"
  skip_provider_registration = true
}

provider "azuread" {
  use_oidc  = false
  tenant_id = "${FAKE_UUID}"
}
HCL
}

# ── Per-layer override files ──────────────────────────────────────────────────

write_core_override() {
  cat > "${REPO_ROOT}/core/localstack.override.tf" <<HCL
# DO NOT COMMIT — generated by scripts/ls-init.sh
# Overrides the azurerm backend + provider for LocalStack Azure testing.

terraform {
  backend "local" {
    path = "terraform.localstack.tfstate"
  }
}
$(provider_block)
HCL
  echo "  wrote core/localstack.override.tf"
}

write_data_override() {
  cat > "${REPO_ROOT}/data/localstack.override.tf" <<HCL
# DO NOT COMMIT — generated by scripts/ls-init.sh

terraform {
  backend "local" {
    path = "terraform.localstack.tfstate"
  }
}
$(provider_block)

# Override remote state reads — use local state files from upstream layers.
# Enforcement rule: sub-modules still never call terraform_remote_state
# directly; this override only affects the tier-root data source.
data "terraform_remote_state" "core" {
  backend = "local"
  config = {
    path = "../core/terraform.localstack.tfstate"
  }
}
HCL
  echo "  wrote data/localstack.override.tf"
}

write_compute_override() {
  cat > "${REPO_ROOT}/compute/localstack.override.tf" <<HCL
# DO NOT COMMIT — generated by scripts/ls-init.sh

terraform {
  backend "local" {
    path = "terraform.localstack.tfstate"
  }
}
$(provider_block)

data "terraform_remote_state" "core" {
  backend = "local"
  config = {
    path = "../core/terraform.localstack.tfstate"
  }
}

data "terraform_remote_state" "data" {
  backend = "local"
  config = {
    path = "../data/terraform.localstack.tfstate"
  }
}
HCL
  echo "  wrote compute/localstack.override.tf"
}

write_workloads_override() {
  cat > "${REPO_ROOT}/workloads/localstack.override.tf" <<HCL
# DO NOT COMMIT — generated by scripts/ls-init.sh

terraform {
  backend "local" {
    path = "terraform.localstack.tfstate"
  }
}
$(provider_block)

data "terraform_remote_state" "core" {
  backend = "local"
  config  = { path = "../core/terraform.localstack.tfstate" }
}

data "terraform_remote_state" "data" {
  backend = "local"
  config  = { path = "../data/terraform.localstack.tfstate" }
}

data "terraform_remote_state" "compute" {
  backend = "local"
  config  = { path = "../compute/terraform.localstack.tfstate" }
}
HCL
  echo "  wrote workloads/localstack.override.tf"
}

write_edge_override() {
  cat > "${REPO_ROOT}/edge/localstack.override.tf" <<HCL
# DO NOT COMMIT — generated by scripts/ls-init.sh

terraform {
  backend "local" {
    path = "terraform.localstack.tfstate"
  }
}
$(provider_block)

data "terraform_remote_state" "core" {
  backend = "local"
  config  = { path = "../core/terraform.localstack.tfstate" }
}

data "terraform_remote_state" "compute" {
  backend = "local"
  config  = { path = "../compute/terraform.localstack.tfstate" }
}
HCL
  echo "  wrote edge/localstack.override.tf"
}

# ── Shared tfvars (dummy values — LocalStack doesn't validate them) ───────────
write_tfvars() {
  local layer=$1
  cat > "${REPO_ROOT}/${layer}/localstack.auto.tfvars" <<HCL
# DO NOT COMMIT — generated by scripts/ls-init.sh
# Provides the minimum required variable values for LocalStack testing.
location     = "eastus2"
environment  = "dev"
bu_code      = "ls"
product_name = "example01"
tenant_id    = "${FAKE_UUID}"
address_space = ["10.0.0.0/16"]
alert_email  = "local@localstack.test"
HCL
  echo "  wrote ${layer}/localstack.auto.tfvars"
}

# ── terraform init each layer ─────────────────────────────────────────────────
tf_init() {
  local layer=$1
  echo "  terraform init -reconfigure (${layer})"
  cd "${REPO_ROOT}/${layer}"
  terraform init -reconfigure -input=false -no-color 2>&1 | grep -E "^(Initializing|Terraform|Error|Warning)" || true
  cd "${REPO_ROOT}"
}

# ── Main ──────────────────────────────────────────────────────────────────────
echo ""
echo "==> Creating LocalStack override files"
write_core_override
write_data_override
write_compute_override
write_workloads_override
write_edge_override

echo ""
echo "==> Creating LocalStack tfvars"
for layer in core data compute workloads edge; do
  write_tfvars "$layer"
done

echo ""
echo "==> Running terraform init for each layer"
for layer in core data compute workloads edge; do
  tf_init "$layer"
done

echo ""
echo "==> Done. LocalStack overrides active."
echo "    Run 'make ls-plan' to plan all layers."
echo "    Run 'make ls-apply' to apply all layers."
echo "    Run 'make ls-teardown' to remove override files."
